#!/bin/bash

export_dir=`mktemp -d`

now=$(date +"%Y-%m-%d %H:%M")
echo "$now" > $export_dir/wikidump.timestamp

cp /var/www/wiki.ros.org/mirror.htaccess $export_dir/.htaccess

cp -a /var/www/wiki.ros.org/data/plugin/custom $export_dir

#hack for default template
cp $export_dir/custom/images/ros_org.png $export_dir/logo.png

#move the theme where we want it
mv $export_dir/custom/rostheme $export_dir


python /var/www/wiki.ros.org/venv/lib/python2.6/site-packages/MoinMoin/script/moin.py \
--config-dir=/var/www/wiki.ros.org/conf/ \
--wiki-url=wiki.ros.org/ export dump \
--target-dir=$export_dir/

sed -i 's+http://www.ros.org/doc/+doc/+g' $export_dir/*.html
sed -i 's+http://ros.org/doc/+doc/+g' $export_dir/*.html
sed -i 's+www.ros.org/++g' $export_dir/*.html

find $export_dir/ -name \*.bag -exec rm -f {} \;
find $export_dir/ -type d -exec chmod 755 {} \;
find $export_dir/ -type f -exec chmod 644 {} \;

# fix references to custom from absolute to relative
find $export_dir -name \*.html -exec sed -i 's+src="/custom/+src="\./custom/+' {} \;

# fix references to rostheme resources
find $export_dir -name \*.html -exec sed -i 's+src="/moin_static197/rostheme/+src="\./rostheme/+' {} \;

# add jquery to all pages
find $export_dir -name \*.html -exec sed -i 's+</head>+<script type="text/javascript" src="\./custom/libraries/jquery\.min\.js"></script></head>+' {} \;

# add rel="canonical" links to all pages using the backlink string
python /var/www/wiki.ros.org/rel_canonical.py $export_dir

# copy export into the available directory, with cleanup
rsync -av $export_dir/ /var/www/wiki.ros.org/wiki_dump --delete

rm -rf $export_dir
